<?php
namespace YahnisElsts\PluginUpdateChecker\v5\Plugin;

class UpdateChecker {
    protected $vcsUrl;
    protected $pluginFile;
    protected $slug;

    public function __construct($url, $pluginFile, $slug) {
        $this->vcsUrl = $url;
        $this->pluginFile = $pluginFile;
        $this->slug = $slug ? $slug : basename($pluginFile, '.php');
        
        add_filter('pre_set_site_transient_update_plugins', array($this, 'check_for_updates'));
        add_filter('plugins_api', array($this, 'inject_plugin_info'), 20, 3);
    }

    public function check_for_updates($transient) {
        if (empty($transient)) {
            $transient = new \stdClass();
        }

        // Fetch remote data safely from GitHub API
        $repo_path = parse_url($this->vcsUrl, PHP_URL_PATH);
        $api_url = 'https://api.github.com/repos' . rtrim($repo_path, '/') . '/releases/latest';
        
        // GitHub API demands a specific User-Agent header or it returns a 403 error
        $response = wp_remote_get($api_url, array(
            'headers' => array(
                'User-Agent' => 'Bare-Bones-SEO-Updater-v1'
            ),
            'timeout' => 10
        ));

        if (is_wp_error($response) || wp_remote_retrieve_response_code($response) !== 200) {
            return $transient;
        }

        $release = json_decode(wp_remote_retrieve_body($response));
        if (empty($release) || empty($release->tag_name)) {
            return $transient;
        }

        $remote_version = ltrim($release->tag_name, 'vV');
        
        // Safely fetch local version
        if (!function_exists('get_plugin_data')) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }
        $plugin_data = get_plugin_data($this->pluginFile);

        if (version_compare($remote_version, $plugin_data['Version'], '>')) {
            $update = new \stdClass();
            $update->slug = $this->slug;
            $update->plugin = plugin_basename($this->pluginFile);
            $update->new_version = $remote_version;
            $update->url = $this->vcsUrl;
            $update->package = $release->zipball_url; // Download link generated by GitHub

            $transient->response[$update->plugin] = $update;
        }

        return $transient;
    }

    public function inject_plugin_info($result, $action, $args) {
        if ($action !== 'plugin_information' || (isset($args->slug) && $args->slug !== $this->slug)) {
            return $result;
        }

        if (!function_exists('get_plugin_data')) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }
        $plugin_data = get_plugin_data($this->pluginFile);
        
        $info = new \stdClass();
        $info->name = $plugin_data['Name'];
        $info->slug = $this->slug;
        $info->version = $plugin_data['Version'];
        $info->author = $plugin_data['Author'];
        $info->homepage = $plugin_data['PluginURI'];
        $info->sections = array(
            'description' => $plugin_data['Description']
        );

        return $info;
    }
}
